spring:
  application:
    name: provider-order
  zipkin:
    base-url: http://localhost:8882

# eureka:
#   client:
#     serviceUrl:
#       defaultZone: http://localhost:8880/eureka/
#   instance:
#     instance-id: ${spring.cloud.client.ipAddress}:${server.port}

feign:
   hystrix:
     enabled: true