server:
  port: 8883

spring:
  application:
    name: provider-order

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8880/eureka/
  instance:
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}