server:
  port: 8808

spring:
  application:
    name: Config-Server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Alex1119/SpringCloud/
          searchPaths: Config
          label: master
          username: #公共仓库可不配置
          password: