server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
   config:
    label: master
    server:
     git:
       uri: https://github.com/Alex1119/SpringCloud/
       search-paths: Config
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8880/eureka/