server:
  port: 8882

spring:
  application:
    name: provider-user

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8880/eureka/
  instance:
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}


#config:
#  serverPort: 8880 #×¢²áÖÐÐÄ¶Ë¿Ú